apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: rwatana/client
      context: js/Features/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: rwatana/comments
      context: js/Features/comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rwatana/event-bus
      context: js/Features/event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rwatana/moderation
      context: js/Features/moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rwatana/posts
      context: js/Features/posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rwatana/query
      context: js/Features/query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: rwatana/loggingserver
      context: go/Features/logging/cmd/loggingServer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.go"
            dest: .
    - image: rwatana/loggingdb
      context: go/Features/logging/cmd/loggingDB
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.go"
            dest: .
    - image: rwatana/loggingdemo
      context: go/Features/logging/cmd/loggingDB
      docker:
        dockerfile: demo.Dockerfile
      sync:
        manual:
          - src: "*.go"
            dest: .
    - image: rwatana/loggingdemojs
      context: go/Features/logging/cmd/loggingserver/sendServer
      docker:
        dockerfile: demo.Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
