apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-server
  template:
    metadata:
      labels:
        app: logging-server
    spec:
      containers:
        - name: logging-server
          image: rwatana/logging-server:latest
---
apiVersion: v1
kind: Service
metadata:
  name: logging-server-srv
spec:
  selector:
    app: logging-server
  ports:
    - name: logging-server
      protocol: TCP
      port: 4006
      targetPort: 4006