apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggingdb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggingdb
  template:
    metadata:
      labels:
        app: loggingdb
    spec:
      containers:
        - name: loggingdb
          image: rwatana/loggingdb


---

apiVersion: v1
kind: Service
metadata:
  name: loggingdb-srv
spec:
  selector:
    app: loggingdb
  ports:
    - name: loggingdb
      protocol: TCP
      port: 3306
      targetPort: 3306